export const TEAM_DELETE_RESET = 'TEAM_DELETE_RESET'
export const TEAM_DELETE_SET_ERROR = 'TEAM_DELETE_SET_ERROR'
export const TEAM_DELETE_SET_DELETED = 'TEAM_DELETE_SET_DELETED'
export const TEAM_DELETE_TOGGLE_LOADING = 'TEAM_DELETE_TOGGLE_LOADING'
