export const TOOK_SHOW_RESET = 'TOOK_SHOW_RESET'
export const TOOK_SHOW_SET_ERROR = 'TOOK_SHOW_SET_ERROR'
export const TOOK_SHOW_SET_RETRIEVED = 'TOOK_SHOW_SET_RETRIEVED'
export const TOOK_SHOW_TOGGLE_LOADING = 'TOOK_SHOW_TOGGLE_LOADING'
