export const TEAM_SHOW_RESET = 'TEAM_SHOW_RESET'
export const TEAM_SHOW_SET_ERROR = 'TEAM_SHOW_SET_ERROR'
export const TEAM_SHOW_SET_RETRIEVED = 'TEAM_SHOW_SET_RETRIEVED'
export const TEAM_SHOW_TOGGLE_LOADING = 'TEAM_SHOW_TOGGLE_LOADING'
