export const CLUB_DELETE_RESET = 'CLUB_DELETE_RESET'
export const CLUB_DELETE_SET_ERROR = 'CLUB_DELETE_SET_ERROR'
export const CLUB_DELETE_SET_DELETED = 'CLUB_DELETE_SET_DELETED'
export const CLUB_DELETE_TOGGLE_LOADING = 'CLUB_DELETE_TOGGLE_LOADING'
