export const GAME_SHOW_RESET = 'GAME_SHOW_RESET'
export const GAME_SHOW_SET_ERROR = 'GAME_SHOW_SET_ERROR'
export const GAME_SHOW_SET_RETRIEVED = 'GAME_SHOW_SET_RETRIEVED'
export const GAME_SHOW_TOGGLE_LOADING = 'GAME_SHOW_TOGGLE_LOADING'
