export const TOOK_DELETE_RESET = 'TOOK_DELETE_RESET'
export const TOOK_DELETE_SET_ERROR = 'TOOK_DELETE_SET_ERROR'
export const TOOK_DELETE_SET_DELETED = 'TOOK_DELETE_SET_DELETED'
export const TOOK_DELETE_TOGGLE_LOADING = 'TOOK_DELETE_TOGGLE_LOADING'
