export const CLUB_SHOW_RESET = 'CLUB_SHOW_RESET'
export const CLUB_SHOW_SET_ERROR = 'CLUB_SHOW_SET_ERROR'
export const CLUB_SHOW_SET_RETRIEVED = 'CLUB_SHOW_SET_RETRIEVED'
export const CLUB_SHOW_TOGGLE_LOADING = 'CLUB_SHOW_TOGGLE_LOADING'
